#!/usr/bin/env bash

# test cases
# travis
# markdown
# dot notation
# nested objects

GOLD=$HOME/opt/gold/bin
GOLDdoc=$GOLD/docs
GOLDbin=$GOLD/bin
mkdir -p "$GOLDdoc"
mkdir -p "$GOLDbin"

banner() { cat<<'EOF'
#!/usr/bin/env gawk -f
# GOLD = Gawk Object Layer
#
# -----------------------------------------------
#                  .-'''-.
#                '   _    \  .---._______
#              /   /` '.   \ |   |\  ___ `'.
#       .--./).   |     \  ' |   | ' |--.\  \
#      /.''\\ |   '      |  '|   | | |    \  '
#     | |  | |\    \     / / |   | | |     |  '
#      \`-' /  `.   ` ..' /  |   | | |     |  |
#      /("'`      '-...-'`   |   | | |     ' .'
#      \ '---.               |   | | |___.' /'
#       /'""'.\              |   |/_______.'/
#      ||     ||             '---'\_______|/
#      \'. __//
#       `'---'
# -----------------------------------------------
# 
EOF
}
gold2md() { gawk '
  NR==1                    { print "\n# "'$1'"\n";               next }
  /^}/                     { print; print "```\n";               next }
  /^(func|BEGIN|END).*}$/) { print "```awk"; print; print "```"; next }
  /^(func|BEGIN|END)/)     { print "```awk"; print;              next }
                           { print $0 } '
}

gold2awk() { banner; gawk '
function dots(s,   x) {
  return gensub(/\.([^0-9])([a-zA-Z0-9_]*)/, 
               "[\"\\1\\2\"]","g",s) 
} 
function subs(s,   x) { 
  for(x in SUBS) gsub(x, SUBS[x],s) 
  return s
}
function line(s) {
  if (s ~ /^}/) { 
    show=0
    return s      
  } else {  
    if (s ~ /^[\t ]*$/)   return s                                 
    s = subs(s)
    if (s ~ /^(func|BEGIN|END).*}$/) return dots(s) 
    if (s ~ /^(func|BEGIN|END)/)     show=1  
    return  ( show ?  dots(s) : "# " s ) }
}
function main(f,    path, used,        s,a) {
  if (used[f]++ == 0) { 
    print "#:::::" path " : " f " :::::::::::::::::::::::::::::"
    while((getline s < f) > 0) 
      if (s ~ /^@include/) 
        main( gensub(/.*"(.*)".*$/, "\\1","g",s), path ": " f, used)
      else if (s ~ /^#DEF/ )  {
        split(s,a," ")
     SUBS["\\<" a[2] "\\>"] = a[3] 
      } else if (f ~ /.*awk$/)
        print subs(s)
      else 
        if ((s !~ /^#!/)  && (s !~ /^# vim/))
          print line(s) }
}
BEGIN { main(ARGV[1]) }
'
}

f=$1
cat $f | gold2md  > ${GOLDdoc}/$f
cat $f | gold2awk > ${GOLDbin}/$f
chmod +x ${GOLDbin}/$f

shift
if   [ -z "$0" ]
then cat - | gawk -f ${GOLDbin}/$f 
else         gawk -f ${GOLDbin}/$f $*
fi
