#!/usr/bin/env bash

cat $1 |
gawk '
function ns(n,    s) {
   while(n-- > 0) s= s "    "
   return s
}
function trim(s) {
  gsub(/^[ \t]*/,"",s)
  gsub(/[ \t]*$/,"",s)
  return s
}
/^#[#]+[ \t]/ { 
     new = split($1,a,"#") - 3
     s = $0
     gsub(/^[#]+[ \t]*/,"",s) 
     s = trim(s)
     link = s
     gsub(/[^a-zA-Z0-9\- ]/,"",link)
     gsub(/[ \t]/,"-",link)
     split(s,a,/[ \t]*:[ \t]/)
     a[1] = trim( a[1] )
     a[2] = trim( a[2] )
     if (length(a) == 1)
          print ns(new) "- [" s    "](#" tolower(link) ") " 
     else print ns(new) "- [" a[1] "](#" tolower(link) ") : " a[2] 
}
END {print ""}'
