#!/usr/bin/env bash
Gold=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

doc() {
  cat $Gold/README.md | gawk '
        BEGIN { FS="\n"; RS="" }
              { print; exit 0  }'
  cat $1 | gawk '
        BEGIN { FS="\n"; RS="" }
        NR==1 && $1~/name=top>/ { next }
              { print ""; print }'
}
if [ "$1" = "-r" ]; then
  f=`find . -type f -name '*.md'`
  if [ -n "$f" ]; then
    for g in $f
    do
      if [ "$Gold/README.md" -nt "$g" ]; then
        h=$(mktemp)
        doc $g > $h
        mv $h $g
      fi
    done
  fi
else
  if [ -f "$1" ]; then 
     h=$(mktemp)
     doc $1 > $h
     mv $h $1
  else
    echo "bad arg [$1]"; exit 1
  fi
fi
